# Generated by Django 2.2.1 on 2019-06-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
    ]
