# Generated by Django 2.2.1 on 2019-06-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_auto_20190614_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='strat_time',
            new_name='start_time',
        ),
    ]
